# Generated by Django 3.2.3 on 2021-05-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name',), 'verbose_name': 'Álbume'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',), 'verbose_name': 'Lista de imagene'},
        ),
    ]
