# Generated by Django 3.2.3 on 2021-05-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('published', 'Publicado'), ('draft', 'Borrador')], default='draft', max_length=10, verbose_name='Estado'),
        ),
    ]
