# Generated by Django 3.2.3 on 2021-05-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Contenido'),
        ),
    ]
