# Generated by Django 3.2.3 on 2021-05-27 11:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-id',), 'verbose_name': 'Servicios disponible'},
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Contenido'),
        ),
    ]
