# Generated by Django 3.2.3 on 2021-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='home_slide', verbose_name='Seleccione imagen')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('caption', models.TextField(max_length=100, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='inactiva', max_length=10, verbose_name='Estado')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
