# Generated by Django 3.2.3 on 2021-05-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',), 'verbose_name': 'Portada'},
        ),
    ]
